name: Build GUI (Windows x64)

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build-pornfetch-gui-windows-x64:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.13 x64
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"
          architecture: x64

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          .\venv\Scripts\activate
          pip install -r requirements.txt
          pip install PySide6 nuitka zstandard pywin32 av
          .\src\frontend\update.ps1

      - name: Build application for Windows x64
        run: |
          mkdir deploy
          Get-ChildItem -Path . -Exclude deploy,venv | Move-Item -Destination deploy
          cd deploy
          ..\venv\Scripts\activate
          echo "yes" | pyside6-deploy -c src/build/pysidedeploy_windows.spec -f -v

      - name: Generate SHA256 Checksum
        run: |
          certUtil -hashfile "deploy\Porn Fetch.exe" SHA256 | findstr /v "hashfile CertUtil" > "deploy\PornFetch_Windows_GUI_x64.sha256"

      - name: Publish SHA256 to GitHub Actions Summary
        shell: bash
        run: |
          echo "### SHA256 Checksum for PornFetch_Windows_GUI_x64.exe" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cat "deploy/PornFetch_Windows_GUI_x64.sha256" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

      - name: Archive Windows x64 build
        uses: actions/upload-artifact@v4
        with:
          name: pyside6-application-windows-x64
          path: "deploy\\Porn Fetch.exe"
